// Copyright 2024 TBONESOFT LLC. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package main

import (
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
	"gorm.io/gorm/schema"

	gorm "github.com/tbonesoft/protoc-gen-go-gorm2/proto/gorm/v1"
)

func (b *builder) genTableNameFunction(g *protogen.GeneratedFile, message *protogen.Message, msgOpts *gorm.GormMessageOptions) {
	g.P(`// TableName overrides the default table name generated by GORM.`)
	g.P(`func (`, message.GoIdent, `ORM) TableName() string {`)

	tableName := schema.NamingStrategy{}.TableName(message.GoIdent.GoName)
	if value := msgOpts.GetTable(); value != "" {
		tableName = value
	}

	g.P(`  return "`, tableName, `"`)
	g.P(`}`)
}

func (b *builder) genConvertFunctions(g *protogen.GeneratedFile, message *protogen.Message, msgOpts *gorm.GormMessageOptions, file *protogen.File) {
	b.genConvertFunctionToPB(g, message, msgOpts, file)
	b.genConvertFunctionToORM(g, message, msgOpts, file)
}

// The type `[]byte` could not be copy value via assign statement, we use `make(...)` and `copy(...)` instead.
const typeBytes = `[]byte`

func (b *builder) genConvertFunctionToPB(g *protogen.GeneratedFile, message *protogen.Message, msgOpts *gorm.GormMessageOptions, file *protogen.File) {
	g.P(``)
	g.P(`func (x *`, message.GoIdent, `ORM) ToPB (ctx `, generateImport("Context", "context", g), `) (rs *`, message.GoIdent, `, err error) {`)
	g.P(`  rs = &`, message.GoIdent, `{}`)
	g.P(``)

	for _, field := range message.Fields {
		goType := b.fieldGoType(g, file, field)
		isTypeBytes := goType == typeBytes

		if !field.Desc.IsList() && !field.Desc.IsMap() && !isTypeBytes {
			g.P(`rs.`, field.GoName, ` = x.`, field.GoName)
			continue
		}

		g.P(``)
		g.P(`  if x.`, field.GoName, ` != nil {`)
		g.P(`    rs.`, field.GoName, ` = make(`, goType, `, len(x.`, field.GoName, `))`)
		g.P(`    copy(rs.`, field.GoName, `, x.`, field.GoName, `)`)
		if b.autoFillNilStringArray && isStringListField(field) {
			g.P(`  } else {`)
			g.P(`    rs.`, field.GoName, ` = []string{}`)
		}
		g.P(`  }`)
		g.P(``)
	}

	g.P(``)
	g.P(`  return rs, err`)
	g.P(`}`)
}

func (b *builder) genConvertFunctionToORM(g *protogen.GeneratedFile, message *protogen.Message, msgOpts *gorm.GormMessageOptions, file *protogen.File) {
	g.P(``)
	g.P(`func (x *`, message.GoIdent, `) ToORM (ctx `, generateImport("Context", "context", g), `) (rs *`, message.GoIdent, `ORM, err error) {`)
	g.P(`  rs = &`, message.GoIdent, `ORM{}`)
	g.P(``)

	for _, field := range message.Fields {
		if !field.Desc.IsList() && !field.Desc.IsMap() {
			g.P(`  rs.`, field.GoName, ` = x.`, field.GoName)
			continue
		}

		g.P(``)
		g.P(`  if x.`, field.GoName, ` != nil {`)

		fieldOpts := parseFieldOptions(field)
		gormTags := fieldOpts.GetTag()
		goType := b.fieldGoType2DriverType(g, file, field, gormTags)
		g.P(`    rs.`, field.GoName, ` = make(`, goType, `, len(x.`, field.GoName, `))`)
		g.P(`    copy(rs.`, field.GoName, `, x.`, field.GoName, `)`)

		g.P(`  }`)
		g.P(``)
	}

	g.P(``)
	g.P(`  return rs, err`)
	g.P(`}`)
}

func isStringListField(field *protogen.Field) bool {
	return field.Desc.IsList() && field.Desc.Kind() == protoreflect.StringKind
}
